### ISSUE TITLE
Upstreaming Hadoop Tools

### ISSUE THREAD

**Issue by dmtucker** [bonibruno/BigInsights#1]
Hey Boni,
I see you have made some updates to scripts from [claudiofahey/isilon-hadoop-tools](https://github.com/claudiofahey/isilon-hadoop-tools), and I was wondering if you had considered pushing them back upstream.
The only reason I ask is because, in the near future, we (the HDFS team) will be looking to create a new script that utilizes PAPI to do some of the things these scripts do (namely, creating users).
It would be helpful if we had a unified view of what is required to do various deployments.
Upstreaming has the added benefit of a PR review too.
I can help if you'd like.

**Comment by dmtucker** [comment]
Also, there have been updates to that script that I don't think you have yet.

**Comment by bonibruno** [comment]
Sounds good to me, but I don’t think I have the right access rights to
upstream my IBM stuff to Claudio’s github site...

**Comment by dmtucker** [comment]
Right, so the way this is typically done is...

1. Fork the upstream repo. (i.e. Go to claudiofahey/ision-hadoop-tools and click Fork in the upper right.)

  * This creates a clone of his repo in your account which you have ownership rights to.

2. Make changes and push them to your fork. (In this case you would clone your fork, insert your changes to the files, commit, and push back to GitHub.)

  * At this point, the only difference between your fork and Claudio's repo is your changes.

3. Go to your fork on GitHub and make a Pull Request.

  * Now Claudio will be alerted that you want to give him some new code, and he can review it, leave feedback and ultimately merge it into his repo.
  * You can see open pull requests against Claudio's code here: https://github.com/claudiofahey/isilon-hadoop-tools/pulls
  * Note: This step only works if your repo is a fork of another repo.
